// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestaoTCC.Core.Models;

#nullable disable

namespace SistemaGestaoTCC.Core.Migrations
{
    [DbContext(typeof(SGTCCContext))]
    [Migration("20250309153905_AdicionarUserActivationTokens")]
    partial class AdicionarUserActivationTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Diretorio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Arquivo__3214EC0709DE1BE0");

                    b.HasIndex(new[] { "Id" }, "UQ__Arquivo__3214EC0659AF81AD")
                        .IsUnique();

                    b.ToTable("Arquivo", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.AtividadeComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AtividadeComentario");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.AvaliadorBanca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("IdBanca")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Avaliado__3214EC07785E3F3B");

                    b.HasIndex("IdBanca");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "Id" }, "UQ__Avaliado__3214EC06E4C2872F")
                        .IsUnique();

                    b.ToTable("AvaliadorBanca", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Banca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataSeminario")
                        .HasColumnType("datetime");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoAluno")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacaoNotaProjeto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Parecer")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Banca__3214EC0763BEC98E");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__Banca__3214EC0688563392")
                        .IsUnique();

                    b.ToTable("Banca", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.CampoDocumentoAvaliacaoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CampoDoc__3214EC07B4B7809F");

                    b.HasIndex("IdCategoria");

                    b.HasIndex(new[] { "Id" }, "UQ__CampoDoc__3214EC069D5D5B6D")
                        .IsUnique();

                    b.ToTable("CampoDocumentoAvaliacaoAluno", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC0733CAB5D7");

                    b.HasIndex(new[] { "Id" }, "UQ__Categori__3214EC06C29F907D")
                        .IsUnique();

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Curso__3214EC078D300E46");

                    b.HasIndex(new[] { "Id" }, "UQ__Curso__3214EC06EA6FFBA6")
                        .IsUnique();

                    b.ToTable("Curso", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.NotaDocumentoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdAvaliadorBanca")
                        .HasColumnType("int");

                    b.Property<int>("IdCampo")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__NotaDocu__3214EC07B9C2A327");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAvaliadorBanca");

                    b.HasIndex("IdCampo");

                    b.HasIndex(new[] { "Id" }, "UQ__NotaDocu__3214EC069F1F206F")
                        .IsUnique();

                    b.ToTable("NotaDocumentoAluno", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.NotaFinalAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdAvaliadorBanca")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__NotaFina__3214EC076FF9237A");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAvaliadorBanca");

                    b.HasIndex(new[] { "Id" }, "UQ__NotaFina__3214EC066E9C820F")
                        .IsUnique();

                    b.ToTable("NotaFinalAluno", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("char(300)")
                        .IsFixedLength();

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("char(300)")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Projeto__3214EC074D88572F");

                    b.HasIndex(new[] { "Id" }, "UQ__Projeto__3214EC0668F8D5F0")
                        .IsUnique();

                    b.ToTable("Projeto", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdArquivo")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoA__3214EC07172078B8");

                    b.HasIndex("IdArquivo");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoA__3214EC06EA6996F7")
                        .IsUnique();

                    b.ToTable("ProjetoArquivo", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoA__3214EC07CDEDCCA7");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoA__3214EC0686E8F3F1")
                        .IsUnique();

                    b.ToTable("ProjetoAtividade", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoAvaliacaoPublica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoA__3214EC07FCCD1D9C");

                    b.HasIndex("IdProjeto");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoA__3214EC061E03045F")
                        .IsUnique();

                    b.ToTable("ProjetoAvaliacaoPublica", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoC__3214EC077F5E0E05");

                    b.HasIndex("IdProjeto");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoC__3214EC06EC319850")
                        .IsUnique();

                    b.ToTable("ProjetoComentario", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<bool>("Entregue")
                        .HasColumnType("bit");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoE__3214EC07FF2E2C97");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoE__3214EC06E0AA35FA")
                        .IsUnique();

                    b.ToTable("ProjetoEntrega", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoEntregaProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEntrega")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoEntregaProjeto");

                    b.HasIndex("IdEntrega");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoEntregaProjeto")
                        .IsUnique();

                    b.ToTable("ProjetoEntregaProjeto", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ProjetoT__3214EC071C20B105");

                    b.HasIndex("IdProjeto");

                    b.HasIndex(new[] { "Id" }, "UQ__ProjetoT__3214EC06278018D2")
                        .IsUnique();

                    b.ToTable("ProjetoTag", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int?>("IdImagem")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC07B2323B37");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdImagem");

                    b.HasIndex(new[] { "Id" }, "UQ__Usuario__3214EC068B29E4A2")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.UsuarioProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("datetime");

                    b.Property<int>("Funcao")
                        .HasColumnType("int");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UsuarioP__3214EC07612D62A1");

                    b.HasIndex("IdProjeto");

                    b.HasIndex("IdUsuario");

                    b.HasIndex(new[] { "Id" }, "UQ__UsuarioP__3214EC06E08B28F9")
                        .IsUnique();

                    b.ToTable("UsuarioProjeto", (string)null);
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.AtividadeComentario", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.ProjetoAtividade", null)
                        .WithMany()
                        .HasForeignKey("IdAtividade")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.AvaliadorBanca", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Banca", "IdBancaNavigation")
                        .WithMany("AvaliadorBancas")
                        .HasForeignKey("IdBanca")
                        .IsRequired()
                        .HasConstraintName("FK__Avaliador__IdBan__08B54D69");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("AvaliadorBancas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Avaliador__IdUsu__07C12930");

                    b.Navigation("IdBancaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Banca", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("Bancas")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__Banca__IdProjeto__0B91BA14");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.CampoDocumentoAvaliacaoAluno", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("CampoDocumentoAvaliacaoAlunos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__CampoDocu__IdCat__0E6E26BF");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.NotaDocumentoAluno", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdAlunoNavigation")
                        .WithMany("NotaDocumentoAlunos")
                        .HasForeignKey("IdAluno")
                        .IsRequired()
                        .HasConstraintName("FK__NotaDocum__IdAlu__09A971A2");

                    b.HasOne("SistemaGestaoTCC.Core.Models.AvaliadorBanca", "IdAvaliadorBancaNavigation")
                        .WithMany("NotaDocumentoAlunos")
                        .HasForeignKey("IdAvaliadorBanca")
                        .IsRequired()
                        .HasConstraintName("FK__NotaDocum__IdAva__0F624AF8");

                    b.HasOne("SistemaGestaoTCC.Core.Models.CampoDocumentoAvaliacaoAluno", "IdCampoNavigation")
                        .WithMany("NotaDocumentoAlunos")
                        .HasForeignKey("IdCampo")
                        .IsRequired()
                        .HasConstraintName("FK__NotaDocum__IdCam__10566F31");

                    b.Navigation("IdAlunoNavigation");

                    b.Navigation("IdAvaliadorBancaNavigation");

                    b.Navigation("IdCampoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.NotaFinalAluno", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdAlunoNavigation")
                        .WithMany("NotaFinalAlunos")
                        .HasForeignKey("IdAluno")
                        .IsRequired()
                        .HasConstraintName("FK__NotaFinal__IdAlu__0A9D95DB");

                    b.HasOne("SistemaGestaoTCC.Core.Models.AvaliadorBanca", "IdAvaliadorBancaNavigation")
                        .WithMany("NotaFinalAlunos")
                        .HasForeignKey("IdAvaliadorBanca")
                        .IsRequired()
                        .HasConstraintName("FK__NotaFinal__IdAva__114A936A");

                    b.Navigation("IdAlunoNavigation");

                    b.Navigation("IdAvaliadorBancaNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoArquivo", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Arquivo", "IdArquivoNavigation")
                        .WithMany("ProjetoArquivos")
                        .HasForeignKey("IdArquivo")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoAr__IdArq__0D7A0286");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoArquivos")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoAr__IdPro__04E4BC85");

                    b.Navigation("IdArquivoNavigation");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoAtividade", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoAtividades")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoAt__IdPro__00200768");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoAvaliacaoPublica", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoAvaliacaoPublicas")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoAv__IdPro__06CD04F7");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ProjetoAvaliacaoPublicas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoAv__IdUsu__05D8E0BE");

                    b.Navigation("IdProjetoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoComentario", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoComentarios")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoCo__IdPro__03F0984C");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ProjetoComentarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoCo__IdUsu__02FC7413");

                    b.Navigation("IdProjetoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoEntrega", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoEntregas")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoEn__IdPro__7E37BEF6");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoEntregaProjeto", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.ProjetoEntrega", "IdEntregaNavigation")
                        .WithMany("ProjetoEntregaProjetos")
                        .HasForeignKey("IdEntrega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjetoEntregaProjeto_Entrega");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoEntregaProjetos")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjetoEntregaProjeto_Projeto");

                    b.Navigation("IdEntregaNavigation");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoTag", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("ProjetoTags")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__ProjetoTa__IdPro__7F2BE32F");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.UserToken", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Usuario", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Curso", "IdCursoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCurso")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__IdCurso__123EB7A3");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Arquivo", "IdImagemNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdImagem")
                        .HasConstraintName("FK__Usuario__IdImage__0C85DE4D");

                    b.Navigation("IdCursoNavigation");

                    b.Navigation("IdImagemNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.UsuarioProjeto", b =>
                {
                    b.HasOne("SistemaGestaoTCC.Core.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("UsuarioProjetos")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioPr__IdPro__02084FDA");

                    b.HasOne("SistemaGestaoTCC.Core.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioProjetos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioPr__IdUsu__01142BA1");

                    b.Navigation("IdProjetoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Arquivo", b =>
                {
                    b.Navigation("ProjetoArquivos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.AvaliadorBanca", b =>
                {
                    b.Navigation("NotaDocumentoAlunos");

                    b.Navigation("NotaFinalAlunos");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Banca", b =>
                {
                    b.Navigation("AvaliadorBancas");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.CampoDocumentoAvaliacaoAluno", b =>
                {
                    b.Navigation("NotaDocumentoAlunos");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Categoria", b =>
                {
                    b.Navigation("CampoDocumentoAvaliacaoAlunos");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Curso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Projeto", b =>
                {
                    b.Navigation("Bancas");

                    b.Navigation("ProjetoArquivos");

                    b.Navigation("ProjetoAtividades");

                    b.Navigation("ProjetoAvaliacaoPublicas");

                    b.Navigation("ProjetoComentarios");

                    b.Navigation("ProjetoEntregaProjetos");

                    b.Navigation("ProjetoEntregas");

                    b.Navigation("ProjetoTags");

                    b.Navigation("UsuarioProjetos");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.ProjetoEntrega", b =>
                {
                    b.Navigation("ProjetoEntregaProjetos");
                });

            modelBuilder.Entity("SistemaGestaoTCC.Core.Models.Usuario", b =>
                {
                    b.Navigation("AvaliadorBancas");

                    b.Navigation("NotaDocumentoAlunos");

                    b.Navigation("NotaFinalAlunos");

                    b.Navigation("ProjetoAvaliacaoPublicas");

                    b.Navigation("ProjetoComentarios");

                    b.Navigation("UsuarioProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
