// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class AvaliadorBanca
{
    public AvaliadorBanca(int idUsuario, int idBanca)
    {
        IdUsuario = idUsuario;
        IdBanca = idBanca;

        AdicionadoEm = DateTime.Now;
    }
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdBanca { get; set; }

    public DateTime AdicionadoEm { get; set; }

    public virtual Banca IdBancaNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<NotaDocumentoAluno> NotaDocumentoAlunos { get; set; } = new List<NotaDocumentoAluno>();

    public virtual ICollection<NotaFinalAluno> NotaFinalAlunos { get; set; } = new List<NotaFinalAluno>();
}