// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Banca
{
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public DateTime DataSeminario { get; set; }

    public int? Parecer { get; set; }

    public string ObservacaoNotaProjeto { get; set; }

    public string ObservacaoAluno { get; set; }

    public string Recomendacao { get; set; }

    public virtual ICollection<AvaliadorBanca> AvaliadorBancas { get; set; } = new List<AvaliadorBanca>();

    public virtual Projeto IdProjetoNavigation { get; set; }
}