// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class CampoDocumentoAvaliacaoAluno
{
    public CampoDocumentoAvaliacaoAluno(string campo, int idCategoria)
    {
        Campo = campo;
        IdCategoria = idCategoria;
    }
    public int Id { get; set; }
    public string Campo { get; set; }
    public int IdCategoria { get; set; }
    public virtual Categoria IdCategoriaNavigation { get; set; }
    public virtual ICollection<NotaDocumentoAluno> NotaDocumentoAlunos { get; set; } = new List<NotaDocumentoAluno>();

    public void UpdateCampo(string campo, int idCategoria)
    {
        Campo = campo;
        IdCategoria = idCategoria;
    }
}