// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Categoria //FALTA IMPLEMENTAR
{
    public int Id { get; set; }

    public string Valor { get; set; }

    public virtual ICollection<CampoDocumentoAvaliacaoAluno> CampoDocumentoAvaliacaoAlunos { get; set; } = new List<CampoDocumentoAvaliacaoAluno>();
}