// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Curso
{
    public Curso(string nome, string descricao)
    {
        Nome = nome;
        Descricao = descricao;

        CriadoEm = DateTime.UtcNow;
    }
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public int? IdImagem { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Arquivo? IdImagemNavigation { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
    public void UpdateCourse(string nome, string descricao)
    {
        Nome = nome;
        Descricao = descricao;

        EditadoEm = DateTime.UtcNow;
    }
    public void UpdateImage(int idImagem)
    {
        IdImagem = idImagem;

        EditadoEm = DateTime.UtcNow;
    }
}