// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class Curso
{
    public Curso(string nome, string descricao)
    {
        Nome = nome;
        Descricao = descricao;
    }

    public int Id { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public void UpdateCourse(string nome, string descricao)
    {
        Nome = nome;
        Descricao = descricao;
    }
}