// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTCC.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Duvida
{
    public Duvida(int idProjeto, int idUsuario, string texto, VisibilidadeDuvidaEnum visibilidade)
    {
        IdProjeto = idProjeto;
        IdUsuario = idUsuario;
        Texto = texto;
        Visibilidade = visibilidade;

        CriadoEm = DateTime.Now;
    }

    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public int IdUsuario { get; set; }

    public string Texto { get; set; }
    
    public VisibilidadeDuvidaEnum Visibilidade { get; set; }

    public RespotaDuvidaEnum Atendida { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<RespostaDuvida> RespostaDuvida { get; set; } = new List<RespostaDuvida>();

    public void Update(int idProjeto, int idUsuario, string texto, VisibilidadeDuvidaEnum visibilidade)
    {

        IdProjeto = idProjeto;
        IdUsuario = idUsuario;
        Texto = texto;
        Visibilidade = visibilidade;

        CriadoEm = DateTime.Now;
    }
}