// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class NotaFinalAluno
{
    public NotaFinalAluno(int idAvaliadorBanca, int idAluno, int nota)
    {
        IdAvaliadorBanca = idAvaliadorBanca;
        IdAluno = idAluno;
        Nota = nota;

        CriadoEm = DateTime.Now;
    }

    public int Id { get; set; }
    public int IdAvaliadorBanca { get; set; }
    public int IdAluno { get; set; }
    public int Nota { get; set; }
    public DateTime CriadoEm { get; set; }
    public virtual Usuario IdAlunoNavigation { get; set; }
    public virtual AvaliadorBanca IdAvaliadorBancaNavigation { get; set; }
}