// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class NotaDocumentoAluno //FALTA IMPLEMENTAR
{
    public int Id { get; set; }

    public int IdAvaliadorBanca { get; set; }

    public int IdCampo { get; set; }

    public int IdAluno { get; set; }

    public int Nota { get; set; }

    public int Tipo { get; set; }

    public virtual Usuario IdAlunoNavigation { get; set; }

    public virtual AvaliadorBanca IdAvaliadorBancaNavigation { get; set; }

    public virtual CampoDocumentoAvaliacaoAluno IdCampoNavigation { get; set; }
}