// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoEntrega
{
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public string Titulo { get; set; }

    public DateTime DataLimite { get; set; }

    public DateTime? DataEnvio { get; set; }

    public bool Entregue { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
}