// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class ProjetoArquivo
{
    public ProjetoArquivo(int idProjeto, int idUsuario, int idArquivo, int versao)
    {
        IdProjeto = idProjeto;
        IdUsuario = idUsuario;
        IdArquivo = idArquivo;
        Versao = versao;
    }
    public int Id { get; set; }

    public int Versao { get; set; }

    public int IdProjeto { get; set; }

    public int IdArquivo { get; set; }

    public int IdUsuario { get; set; }

    public virtual Arquivo IdArquivoNavigation { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}