// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class ProjetoEntrega
{
    public ProjetoEntrega(int idProjeto, string titulo, DateTime dataLimite, bool entregue)
    {
        IdProjeto = idProjeto;
        Titulo = titulo;
        DataLimite = dataLimite;
        Entregue = entregue;

        DataEnvio = DateTime.UtcNow;
        CriadoEm = DateTime.UtcNow;
    }
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public string Titulo { get; set; }

    public DateTime DataLimite { get; set; }

    public DateTime? DataEnvio { get; set; }

    public bool Entregue { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
    public void UpdateEntrega(string titulo, DateTime dataLimite, bool entregue)
    {
        Titulo = titulo;
        DataLimite = dataLimite;
        Entregue = entregue;

        EditadoEm = DateTime.UtcNow;
    }
}