// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTcc.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoAtividade
{
    public ProjetoAtividade(int idProjeto, string nome, string descricao)
    {
        IdProjeto = idProjeto;
        Nome = nome;
        Descricao = descricao;
        Estado = ProjetoAtividadeEnum.Created;

        CriadoEm = DateTime.UtcNow;
    }

    //public int IdAtividade { get; set; }
    public int Id { get; set; }
    public int IdProjeto { get; set; }
    public string Nome { get; set; }
    public string Descricao { get; set; }
    public ProjetoAtividadeEnum Estado { get; set; }
    public virtual Projeto IdProjetoNavigation { get; set; }
    public DateTime CriadoEm { get; set; }
    public DateTime? EditadoEm { get; set; }
    public void UpdateAtividade(int idProjeto, string nome, string descricao)
    {
        IdProjeto = idProjeto;
        Nome = nome;
        Descricao = descricao;

        EditadoEm = DateTime.UtcNow;
    }
    public void Finish()
    {
        if (Estado == ProjetoAtividadeEnum.Created || Estado == ProjetoAtividadeEnum.InProgress)
        {
            Estado = ProjetoAtividadeEnum.Finished;
        }
    }
}