// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTCC.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Projeto
{
    public Projeto(string nome, string descricao, string justificativa)
    {
        Nome = nome;
        Descricao = descricao;
        Justificativa = justificativa;
        DataInicio = DateTime.UtcNow;
        CriadoEm = DateTime.UtcNow;
    }
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public string Justificativa { get; set; }

    public int? IdImagem { get; set; }

    public DateTime DataInicio { get; set; }

    public DateTime? DataFim { get; set; }

    public bool Aprovado { get; set; }

    public StatusProjeto Estado { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual ICollection<Anotacao> Anotacaos { get; set; } = new List<Anotacao>();

    public virtual ICollection<Banca> Bancas { get; set; } = new List<Banca>();

    public virtual ICollection<Bibliografia> Bibliografia { get; set; } = new List<Bibliografia>();

    public virtual ICollection<Duvida> Duvida { get; set; } = new List<Duvida>();

    public virtual Arquivo IdImagemNavigation { get; set; }

    public virtual ICollection<ProjetoArquivo> ProjetoArquivos { get; set; } = new List<ProjetoArquivo>();

    public virtual ICollection<ProjetoAtividade> ProjetoAtividades { get; set; } = new List<ProjetoAtividade>();

    public virtual ICollection<ProjetoAvaliacaoPublica> ProjetoAvaliacaoPublicas { get; set; } = new List<ProjetoAvaliacaoPublica>();

    public virtual ICollection<ProjetoComentario> ProjetoComentarios { get; set; } = new List<ProjetoComentario>();

    public virtual ICollection<ProjetoEntrega> ProjetoEntregas { get; set; } = new List<ProjetoEntrega>();

    public virtual ICollection<ProjetoTag> ProjetoTags { get; set; } = new List<ProjetoTag>();

    public virtual ICollection<Proposta> Proposta { get; set; } = new List<Proposta>();

    public virtual ICollection<SeminarioProjeto> SeminarioProjetos { get; set; } = new List<SeminarioProjeto>();

    public virtual ICollection<UsuarioProjeto> UsuarioProjetos { get; set; } = new List<UsuarioProjeto>();
    public void Update(string nome, string descricao, string justificativa)
    {
        Nome = nome;
        Descricao = descricao;
        Justificativa = justificativa;
    }
    public void UpdateImage(int idImagem)
    {
        IdImagem = idImagem;
    }
    public void Start()
    {
        if (Estado == StatusProjeto.Created)
        {
            Estado = StatusProjeto.InProgress;
        }
    }
    public void Finish()
    {
        if (Estado == StatusProjeto.Created || Estado == StatusProjeto.InProgress)
        {
            Estado = StatusProjeto.Finished;
            DataFim = DateTime.UtcNow;
        }
    }
    public void Cancel()
    {
        if (Estado == StatusProjeto.Created || Estado == StatusProjeto.InProgress)
        {
            Estado = StatusProjeto.Canceled;
        }
        else if (Estado == StatusProjeto.Canceled)
        {
            Estado = StatusProjeto.InProgress;
        }
    }
}