// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoEntrega
{
    public ProjetoEntrega(int idProjeto, string titulo, DateTime dataLimite, DateTime? dataEnvio, bool entregue)
    {
        IdProjeto = idProjeto;
        Titulo = titulo;
        DataLimite = dataLimite;
        DataEnvio = dataEnvio;
        Entregue = entregue;
    }

    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public string Titulo { get; set; }

    public DateTime DataLimite { get; set; }

    public DateTime? DataEnvio { get; set; }

    public bool Entregue { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
}