// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTCC.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class ProjetoAtividade ///VAI MUDAR///
{
    public ProjetoAtividade(int idProjeto, string nome, string descricao)
    {
        IdProjeto = idProjeto;
        Nome = nome;
        Descricao = descricao;

        CriadoEm = DateTime.Now;
    }
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public int IdUsuario { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public ProjetoAtividadeEnum Estado { get; set; }

    public int DuracaoEstimada { get; set; }

    public int Prioridade { get; set; }

    public DateTime? DataInicio { get; set; }

    public DateTime? DataEntrega { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual ICollection<AtividadeComentario> AtividadeComentarios { get; set; } = new List<AtividadeComentario>();

    public virtual Projeto IdProjetoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
    public void UpdateAtividade(int idProjeto, string nome, string descricao)
    {
        IdProjeto = idProjeto;
        Nome = nome;
        Descricao = descricao;
        EditadoEm = DateTime.UtcNow;
    }
    public void Finish()
    {
        if (Estado == ProjetoAtividadeEnum.Created || Estado == ProjetoAtividadeEnum.InProgress)
        {
            Estado = ProjetoAtividadeEnum.Finished;
        }
    }
    public void Start()
    {
        if (Estado == ProjetoAtividadeEnum.Created)
        {
            Estado = ProjetoAtividadeEnum.InProgress;
        }
    }
}