// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoArquivo
{
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public int IdArquivo { get; set; }

    public virtual Arquivo IdArquivoNavigation { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
}