// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoComentario
{
    public ProjetoComentario(int idUsuario, int idProjeto, string comentario)
    {
        IdUsuario = idUsuario;
        IdProjeto = idProjeto;
        Comentario = comentario;

        CriadoEm = DateTime.UtcNow;
    }
    public int Id { get; set; }
    public int IdUsuario { get; set; }
    public int IdProjeto { get; set; }
    public string Comentario { get; set; }
    public DateTime CriadoEm { get; set; }
    public DateTime? EditadoEm { get; set; }
    public virtual Projeto IdProjetoNavigation { get; set; }
    public virtual Usuario IdUsuarioNavigation { get; set; }

    public void UpdateComment(int idUsuario, int idProjeto, string comentario)
    {
        IdUsuario = idUsuario;
        IdProjeto = idProjeto;
        Comentario = comentario;

        EditadoEm = DateTime.UtcNow;    
    }
}