// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTcc.Core.Enums;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoAvaliacaoPublica
{
    public ProjetoAvaliacaoPublica(int idUsuario, int idProjeto, AvaliacaoEnum avaliacao)
    {
        IdUsuario = idUsuario;
        IdProjeto = idProjeto;
        Avaliacao = avaliacao;

        DataAvaliacao = DateTime.UtcNow;
    }

    public int Id { get; set; }
    public int IdUsuario { get; set; }
    public int IdProjeto { get; set; }
    public AvaliacaoEnum Avaliacao { get; set; }
    public DateTime DataAvaliacao { get; set; }
    public virtual Projeto IdProjetoNavigation { get; set; }
    public virtual Usuario IdUsuarioNavigation { get; set; }
}