// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTcc.Core.Models;

public partial class ProjetoAtividade
{
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public int IdAtividade { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public int Estado { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
}