// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Propostum
{
    public int Id { get; set; }

    public int IdProjeto { get; set; }

    public string AtividadesPropostas { get; set; }

    public DateTime ContribuicaoAgenda { get; set; }

    public int Parecer { get; set; }

    public string Sugestao { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Projeto IdProjetoNavigation { get; set; }
}