// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTCC.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Proposta
{
    public Proposta(int idProjeto, string atividadesPropostas, string contribuicaoAgenda, string sugestao)
    {
        IdProjeto = idProjeto;
        AtividadesPropostas = atividadesPropostas;
        ContribuicaoAgenda = contribuicaoAgenda;
        Sugestao = sugestao;

        CriadoEm = DateTime.UtcNow;
        Parecer = ParecerPropostaEnum.NaoAvaliado;
    }
    public int Id { get; set; }
    public int IdProjeto { get; set; }
    public string AtividadesPropostas { get; set; }
    public string ContribuicaoAgenda { get; set; }
    public string Sugestao { get; set; }
    public ParecerPropostaEnum Parecer { get; set; }
    public DateTime CriadoEm { get; set; }
    public DateTime? EditadoEm { get; set; }
    public virtual Projeto IdProjetoNavigation { get; set; }

    public void Update(string atividadesPropostas, string contribuicaoAgenda, string sugestao)
    {
        AtividadesPropostas = atividadesPropostas;
        ContribuicaoAgenda = contribuicaoAgenda;
        Sugestao = sugestao;

        EditadoEm = DateTime.UtcNow;
    }

}