// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace SistemaGestaoTCC.Core.Models;

public partial class RelatorioAcompanhamento
{
    public RelatorioAcompanhamento(int idProfessor, int idProjeto, string titulo, string descricao, int duracaoEncontro, DateTime dataRealizacao)
    {
        IdProfessor = idProfessor;
        IdProjeto = idProjeto;
        Titulo = titulo;
        Descricao = descricao;
        DuracaoEncontro = duracaoEncontro;
        DataRealizacao = dataRealizacao;

        CriadoEm = DateTime.Now;
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] 
    public int Id { get; set; }

    [Required]
    public int IdProfessor { get; set; }

    [Required]
    public int IdProjeto { get; set; }

    [Column(TypeName = "CHAR")] 
    [MaxLength(255)]
    public string? Titulo { get; set; } 

    [Required]
    [Column(TypeName = "NVARCHAR(MAX)")]
    public string Descricao { get; set; }

    [Required]
    public int DuracaoEncontro { get; set; }

    [Required]
    public DateTime DataRealizacao { get; set; }

    [Required]
    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; } 

    public virtual Projeto IdProjetoNavigation { get; set; }
    [ForeignKey("IdProfessor")]
    public virtual Usuario IdUsuarioNavigation { get; set; }

    public void UpdateRelatorio(int idProfessor, int idProjeto, string titulo, string descricao, int duracaoEncontro, DateTime dataRealizacao)
    {
        IdProfessor = idProfessor;
        IdProjeto = idProjeto;
        Titulo = titulo;
        Descricao = descricao;
        DuracaoEncontro = duracaoEncontro;
        DataRealizacao = dataRealizacao;

        EditadoEm = DateTime.Now;
    }
}