// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class RespostaDuvida
{
    public RespostaDuvida(int idDuvida, int idUsuario, string texto)
    {
        IdDuvida = idDuvida;
        IdUsuario = idUsuario;
        Texto = texto;

        CriadoEm = DateTime.UtcNow;
    }
    public int Id { get; set; }

    public int IdDuvida { get; set; }

    public int IdUsuario { get; set; }

    public string Texto { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Duvida IdDuvidaNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}