// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Seminario
{
    public Seminario(int idUsuario, string requisitos, DateTime data)
    {
        IdUsuario = idUsuario;
        Requisitos = requisitos;
        Data = data;
        
        CriadoEm = DateTime.UtcNow;
    }

    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string Requisitos { get; set; }

    public DateTime Data { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? EditadoEm { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<SeminarioProjeto> SeminarioProjetos { get; set; } = new List<SeminarioProjeto>();
    public void UpdateSeminario(int idUsuario, string requisitos, DateTime data)
    {
        IdUsuario = idUsuario;
        Requisitos = requisitos;
        Data = data;
        EditadoEm = DateTime.UtcNow;
    }
}