// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SistemaGestaoTCC.Core.Models;

public partial class SGTCCContext : DbContext
{
    public SGTCCContext(DbContextOptions<SGTCCContext> options)
        : base(options)
    {
    }
    public virtual DbSet<ProjetoEntregaProjeto> ProjetoEntregaProjetos { get; set; }   
    public virtual DbSet<Arquivo> Arquivo { get; set; }

    //public virtual DbSet<AtividadeProposta> AtividadeProposta { get; set; }
    public virtual DbSet<AtividadeComentario> AtividadeComentario { get; set; }
    public virtual DbSet<AvaliadorBanca> AvaliadorBanca { get; set; }
    public DbSet<PasswordResetToken> PasswordResetTokens { get; set; }
    public virtual DbSet<Banca> Banca { get; set; }

    public DbSet<UserToken> UserTokens { get; set; }

    public DbSet<UserActivationToken> UserActivationTokens { get; set; }


    public virtual DbSet<CampoDocumentoAvaliacaoAluno> CampoDocumentoAvaliacaoAluno { get; set; }

    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Curso> Curso { get; set; }

    public virtual DbSet<NotaDocumentoAluno> NotaDocumentoAluno { get; set; }

    public virtual DbSet<NotaFinalAluno> NotaFinalAluno { get; set; }

    public virtual DbSet<Projeto> Projeto { get; set; }

    public virtual DbSet<ProjetoArquivo> ProjetoArquivo { get; set; }

    public virtual DbSet<ProjetoAtividade> ProjetoAtividade { get; set; }

    public virtual DbSet<ProjetoAvaliacaoPublica> ProjetoAvaliacaoPublica { get; set; }

    public virtual DbSet<ProjetoComentario> ProjetoComentario { get; set; }

    public virtual DbSet<ProjetoEntrega> ProjetoEntrega { get; set; }

    public virtual DbSet<ProjetoTag> ProjetoTag { get; set; }

    //public virtual DbSet<Tag> Tag { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioProjeto> UsuarioProjeto { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ProjetoEntregaProjeto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoEntregaProjeto");

            entity.ToTable("ProjetoEntregaProjeto");

            entity.HasIndex(e => e.Id, "UQ__ProjetoEntregaProjeto").IsUnique();

            entity.HasOne(d => d.IdEntregaNavigation)
                .WithMany(p => p.ProjetoEntregaProjetos)
                .HasForeignKey(d => d.IdEntrega)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProjetoEntregaProjeto_Entrega");

            entity.HasOne(d => d.IdProjetoNavigation)
                .WithMany(p => p.ProjetoEntregaProjetos)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProjetoEntregaProjeto_Projeto");
        });

        modelBuilder.Entity<Arquivo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Arquivo__3214EC0709DE1BE0");

            entity.ToTable("Arquivo");

            entity.HasIndex(e => e.Id, "UQ__Arquivo__3214EC0659AF81AD").IsUnique();

            entity.Property(e => e.CriadoEm).HasColumnType("datetime");
            entity.Property(e => e.Diretorio)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EditadoEm).HasColumnType("datetime");
            entity.Property(e => e.NomeOriginal)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Extensao)
                .IsRequired()
                .HasMaxLength(255);
        });

        //modelBuilder.Entity<AtividadeProposta>(entity =>
        //{
        //    entity.HasKey(e => e.Id).HasName("PK__Atividad__3214EC072EAB3EA5");

        //    entity.HasIndex(e => e.Id, "UQ__Atividad__3214EC06B4D59E8D").IsUnique();

        //    entity.Property(e => e.Descricao)
        //        .IsRequired()
        //        .HasMaxLength(300);
        //    entity.Property(e => e.Nome)
        //        .IsRequired()
        //        .HasMaxLength(50);
        //});

        modelBuilder.Entity<AvaliadorBanca>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Avaliado__3214EC07785E3F3B");

            entity.ToTable("AvaliadorBanca");

            entity.HasIndex(e => e.Id, "UQ__Avaliado__3214EC06E4C2872F").IsUnique();

            entity.HasOne(d => d.IdBancaNavigation).WithMany(p => p.AvaliadorBancas)
                .HasForeignKey(d => d.IdBanca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Avaliador__IdBan__08B54D69");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.AvaliadorBancas)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Avaliador__IdUsu__07C12930");
            entity.Property(e => e.AdicionadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Banca>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Banca__3214EC0763BEC98E");

            entity.ToTable("Banca");

            entity.HasIndex(e => e.Id, "UQ__Banca__3214EC0688563392").IsUnique();

            entity.Property(e => e.DataSeminario).HasColumnType("datetime");
            entity.Property(e => e.ObservacaoAluno).HasMaxLength(500);
            entity.Property(e => e.ObservacaoNotaProjeto).HasMaxLength(500);
            entity.Property(e => e.Recomendacao).HasMaxLength(500);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.Bancas)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Banca__IdProjeto__0B91BA14");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<CampoDocumentoAvaliacaoAluno>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CampoDoc__3214EC07B4B7809F");

            entity.ToTable("CampoDocumentoAvaliacaoAluno");

            entity.HasIndex(e => e.Id, "UQ__CampoDoc__3214EC069D5D5B6D").IsUnique();

            entity.Property(e => e.Campo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.CampoDocumentoAvaliacaoAlunos)
                .HasForeignKey(d => d.IdCategoria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CampoDocu__IdCat__0E6E26BF");
        });

        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0733CAB5D7");

            entity.HasIndex(e => e.Id, "UQ__Categori__3214EC06C29F907D").IsUnique();

            entity.Property(e => e.Valor)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Curso>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Curso__3214EC078D300E46");

            entity.ToTable("Curso");

            entity.HasIndex(e => e.Id, "UQ__Curso__3214EC06EA6FFBA6").IsUnique();

            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime")
                .IsRequired(true);
            entity.Property(e => e.EditadoEm)
                .HasColumnType("datetime");
            entity.HasOne(d => d.IdImagemNavigation).WithMany(p => p.Cursos)
                .HasForeignKey(d => d.IdImagem)
                .HasConstraintName("FK__Curso__IdImage__0C85DE4D");
        });

        modelBuilder.Entity<NotaDocumentoAluno>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotaDocu__3214EC07B9C2A327");

            entity.ToTable("NotaDocumentoAluno");

            entity.HasIndex(e => e.Id, "UQ__NotaDocu__3214EC069F1F206F").IsUnique();

            entity.HasOne(d => d.IdAlunoNavigation).WithMany(p => p.NotaDocumentoAlunos)
                .HasForeignKey(d => d.IdAluno)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NotaDocum__IdAlu__09A971A2");

            entity.HasOne(d => d.IdAvaliadorBancaNavigation).WithMany(p => p.NotaDocumentoAlunos)
                .HasForeignKey(d => d.IdAvaliadorBanca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NotaDocum__IdAva__0F624AF8");

            entity.HasOne(d => d.IdCampoNavigation).WithMany(p => p.NotaDocumentoAlunos)
                .HasForeignKey(d => d.IdCampo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NotaDocum__IdCam__10566F31");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<NotaFinalAluno>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotaFina__3214EC076FF9237A");

            entity.ToTable("NotaFinalAluno");

            entity.HasIndex(e => e.Id, "UQ__NotaFina__3214EC066E9C820F").IsUnique();

            entity.HasOne(d => d.IdAlunoNavigation).WithMany(p => p.NotaFinalAlunos)
                .HasForeignKey(d => d.IdAluno)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NotaFinal__IdAlu__0A9D95DB");

            entity.HasOne(d => d.IdAvaliadorBancaNavigation).WithMany(p => p.NotaFinalAlunos)
                .HasForeignKey(d => d.IdAvaliadorBanca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NotaFinal__IdAva__114A936A");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Projeto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Projeto__3214EC074D88572F");

            entity.ToTable("Projeto");

            entity.HasIndex(e => e.Id, "UQ__Projeto__3214EC0668F8D5F0").IsUnique();

            entity.Property(e => e.DataFim).HasColumnType("datetime");
            entity.Property(e => e.DataInicio).HasColumnType("datetime");
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Justificativa)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
            entity.HasOne(d => d.IdImagemNavigation).WithMany(p => p.Projetos)
                .HasForeignKey(d => d.IdImagem)
                .HasConstraintName("FK__Projeto__IdImage__0C85DE4D");

        });

        modelBuilder.Entity<ProjetoArquivo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoA__3214EC07172078B8");

            entity.ToTable("ProjetoArquivo");

            entity.HasIndex(e => e.Id, "UQ__ProjetoA__3214EC06EA6996F7").IsUnique();

            entity.HasOne(d => d.IdArquivoNavigation).WithMany(p => p.ProjetoArquivos)
                .HasForeignKey(d => d.IdArquivo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAr__IdArq__0D7A0286");

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoArquivos)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAr__IdPro__04E4BC85");
        });

        modelBuilder.Entity<ProjetoAtividade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoA__3214EC07CDEDCCA7");

            entity.ToTable("ProjetoAtividade");

            entity.HasIndex(e => e.Id, "UQ__ProjetoA__3214EC0686E8F3F1").IsUnique();

            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoAtividades)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAt__IdPro__00200768");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
            entity.Property(e => e.EditadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<ProjetoAvaliacaoPublica>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoA__3214EC07FCCD1D9C");

            entity.ToTable("ProjetoAvaliacaoPublica");

            entity.HasIndex(e => e.Id, "UQ__ProjetoA__3214EC061E03045F").IsUnique();

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoAvaliacaoPublicas)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAv__IdPro__06CD04F7");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ProjetoAvaliacaoPublicas)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoAv__IdUsu__05D8E0BE");
        });

        modelBuilder.Entity<ProjetoComentario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoC__3214EC077F5E0E05");

            entity.ToTable("ProjetoComentario");

            entity.HasIndex(e => e.Id, "UQ__ProjetoC__3214EC06EC319850").IsUnique();

            entity.Property(e => e.Comentario)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoComentarios)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoCo__IdPro__03F0984C");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.ProjetoComentarios)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoCo__IdUsu__02FC7413");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
            entity.Property(e => e.EditadoEm)
                .HasColumnType("datetime")
                .IsRequired(false);
        });

        modelBuilder.Entity<ProjetoEntrega>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoE__3214EC07FF2E2C97");

            entity.ToTable("ProjetoEntrega");

            entity.HasIndex(e => e.Id, "UQ__ProjetoE__3214EC06E0AA35FA").IsUnique();

            entity.Property(e => e.DataEnvio).HasColumnType("datetime");
            entity.Property(e => e.DataLimite).HasColumnType("datetime");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoEntregas)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoEn__IdPro__7E37BEF6");
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
            entity.Property(e => e.EditadoEm)
                .HasColumnType("datetime")
                .IsRequired(false);
        });

        modelBuilder.Entity<ProjetoTag>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProjetoT__3214EC071C20B105");

            entity.ToTable("ProjetoTag");

            entity.HasIndex(e => e.Id, "UQ__ProjetoT__3214EC06278018D2").IsUnique();

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.ProjetoTags)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProjetoTa__IdPro__7F2BE32F");
        });

        //modelBuilder.Entity<Tag>(entity =>
        //{
        //    entity.HasKey(e => e.Id).HasName("PK__Tag__3214EC0767C8A121");

        //    entity.ToTable("Tag");

        //    entity.HasIndex(e => e.Id, "UQ__Tag__3214EC06FE0ED4C4").IsUnique();

        //    entity.Property(e => e.Nome)
        //        .IsRequired()
        //        .HasMaxLength(50);
        //});

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3214EC07B2323B37");

            entity.ToTable("Usuario");

            entity.HasIndex(e => e.Id, "UQ__Usuario__3214EC068B29E4A2").IsUnique();

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Senha)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.UltimoAcesso)
                .HasColumnType("datetime")
                .IsRequired(false);

            entity.HasOne(d => d.IdCursoNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdCurso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Usuario__IdCurso__123EB7A3");

            entity.HasOne(d => d.IdImagemNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdImagem)
                .HasConstraintName("FK__Usuario__IdImage__0C85DE4D")
                .IsRequired(false);
            entity.Property(e => e.CriadoEm)
                .HasColumnType("datetime");
            entity.Property(e => e.EditadoEm)
                .HasColumnType("datetime")
                .IsRequired(false);
        });

        modelBuilder.Entity<UsuarioProjeto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioP__3214EC07612D62A1");

            entity.ToTable("UsuarioProjeto");

            entity.HasIndex(e => e.Id, "UQ__UsuarioP__3214EC06E08B28F9").IsUnique();

            entity.HasOne(d => d.IdProjetoNavigation).WithMany(p => p.UsuarioProjetos)
                .HasForeignKey(d => d.IdProjeto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioPr__IdPro__02084FDA");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioProjetos)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioPr__IdUsu__01142BA1");
            entity.Property(e => e.Funcao)
                .IsRequired(true);
            entity.Property(e => e.AdicionadoEm)
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<AtividadeComentario>()
       .HasOne<ProjetoAtividade>()
       .WithMany()
       .HasForeignKey(ac => ac.IdAtividade)
       .OnDelete(DeleteBehavior.NoAction);

        modelBuilder.Entity<AtividadeComentario>()
            .HasOne<Usuario>()
            .WithMany()
            .HasForeignKey(ac => ac.IdUsuario)
            .OnDelete(DeleteBehavior.NoAction);
        OnModelCreatingPartial(modelBuilder);
    }
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}