// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
//using System;
//using System.Collections.Generic;

//namespace SistemaGestaoTcc.Core.Models;

//public partial class Tag   NÃO ESTÁ SENDO UTILIZADA
//{
//    public int Id { get; set; }

//    public string Nome { get; set; }
//}