// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace SistemaGestaoTCC.Core.Models;

public partial class UserActivationToken
{
    [Key]
    public int Id { get; set; }

    [Required]
    public int UserId { get; set; }

    [Required]
    public string Token { get; set; }

    public DateTime ExpirationDate { get; set; }

    [ForeignKey("UserId")]
    public Usuario User { get; set; }
}