// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SistemaGestaoTCC.Core.Enums;
using System;
using System.Collections.Generic;

namespace SistemaGestaoTCC.Core.Models;

public partial class Usuario
{
    public Usuario(int idCurso, string nome, string email, 
        string senha, PapelEnum papel)
    {
        IdCurso = idCurso;
        Nome = nome;
        Email = email;
        Senha = senha;
        Papel = papel;

        CriadoEm = DateTime.Now;

    }
    public int Id { get; set; }
    public int IdCurso { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Senha { get; set; }
    public PapelEnum Papel { get; set; }
    public int? IdImagem { get; set; }
    public DateTime? UltimoAcesso { get; set; }
    public DateTime CriadoEm {  get; set; }
    public DateTime? EditadoEm { get; set; }
    public virtual ICollection<AvaliadorBanca> AvaliadorBancas { get; set; } = new List<AvaliadorBanca>();

    public virtual Curso IdCursoNavigation { get; set; }

    public virtual Arquivo IdImagemNavigation { get; set; }

    public virtual ICollection<NotaDocumentoAluno> NotaDocumentoAlunos { get; set; } = new List<NotaDocumentoAluno>();

    public virtual ICollection<NotaFinalAluno> NotaFinalAlunos { get; set; } = new List<NotaFinalAluno>();

    public virtual ICollection<ProjetoAvaliacaoPublica> ProjetoAvaliacaoPublicas { get; set; } = new List<ProjetoAvaliacaoPublica>();

    public virtual ICollection<ProjetoComentario> ProjetoComentarios { get; set; } = new List<ProjetoComentario>();

    public virtual ICollection<UsuarioProjeto> UsuarioProjetos { get; set; } = new List<UsuarioProjeto>();

<<<<<<< HEAD
    public void Update(string nome, string email, int idCurso)
=======
    public void Update( string nome, string email)
>>>>>>> 4865eafeceed53e3f2acb96c61f7b259be1902c0
    {

        Nome = nome;
        Email = email;
<<<<<<< HEAD
        IdCurso = idCurso;
=======
>>>>>>> 4865eafeceed53e3f2acb96c61f7b259be1902c0

        EditadoEm = DateTime.Now;
    }
}